image: python:3.9

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python manage.py test

pages:
  stage: deploy
  script:
    - pip install -r requirements.txt
    # Collecter les fichiers statiques
    - python manage.py collectstatic --noinput
    - mv staticfiles/ public/
    # Si vous avez un build frontend (optionnel)
    # - mkdir public
    # - cp -r build/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "new"